# Generated by Django 4.1.13 on 2024-05-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="position",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
